### ISSUE TITLE
how ...

### ISSUE THREAD

**Issue by denisdemais** [chazomaticus/libbmpread#3]
can set/get a pixel?

**Comment by camilleg** [comment]
See https://github.com/chazomaticus/libbmpread/blob/master/bmpread.h .  How pixels are stored depends on the flags you passed.  But typically, accessing a pixel will look like a bmpread_t's rgb_data[x + height * y].

**Comment by chazomaticus** [comment]
Thanks, @camilleg, you're absolutely right!

@denisdemais, essentially the only API in this library is a function to read the entire bitmap into memory.  From there, the raw red, green, and blue color components of each pixel are exposed, so you can do whatever you want with them.  As @camilleg says, how the pixels are laid out in that buffer depends on the flags passed in, but to clarify, the default layout is left to right, bottom to top, and unless you're loading small images (1x1 or 2x2), simply 3 bytes (R, G, and B color components in order) per pixel.

Thus, a single pixel (at position `x,y` where `0,0` is the top left corner like you'd expect) can *usually, depending on flags,* be accessed with:

```c
// I didn't verify the math here; YMMV.
int line = bmp.height - 1 - y;  // To compensate for bottom-first order.
unsigned char red   = bmp.rgb_data[line * bmp.width + x * 3 + 0];
unsigned char green = bmp.rgb_data[line * bmp.width + x * 3 + 1];
unsigned char blue  = bmp.rgb_data[line * bmp.width + x * 3 + 2];
```

Setting pixels works with the same formula.
